version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: p45sw0rdd
      MYSQL_USER: mysql_tads_admin
      MYSQL_PASSWORD: mysql_tads_password
      MYSQL_DATABASE: tads_db
    volumes:
      - dbbase:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      PMA_PASSWORD: p45sw0rdd

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    environment:
      - DB_USERNAME=admin_tads
      - DB_PASSWORD=p@ssw0rdT4ad5
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"

volumes:
  dbbase:
