# Use a imagem base do Ubuntu
FROM ubuntu:latest

# Mantenha o sistema atualizado e instale pacotes necessários
RUN apt-get update && apt-get install -y \
    openjdk-17-jdk \
    wget \
    curl \
    gnupg2 \
    ca-certificates \
    && apt-get clean

# Defina o diretório de trabalho
WORKDIR /app

# Copie o jar da sua aplicação para dentro do contêiner
COPY target/chatBotTads-0.0.1-SNAPSHOT.jar /app/chatBotTads.jar

# Exponha a porta que sua aplicação usa
EXPOSE 8080

# Comando para executar a aplicação
ENTRYPOINT ["java", "-jar", "/app/chatBotTads.jar"]
